### ISSUE TITLE
Clarification question about the default value after interacting with the host element

### ISSUE THREAD

**Issue by caridy** [a11y-api/a11y-api#106]
This question is mostly about the default semantic specified via the shadow root, and when will it be used. Here are a couple of examples:

### What happen when the attribute is removed from the host?

```js
element.setAttribute("aria-checked", "true");
element.shadowRoot.ariaChecked = true;
element.removeAttribute("aria-checked");
// what will be the value observed by the reader for checked? true?
```

### What happen when the property is set to null on the host?

```js
element.shadowRoot.ariaChecked = true;
element.ariaChecked = null;
// what will be the value observed by the reader for checked? true?
```

/cc @davidturissini

**Comment by robdodson** [comment]
I believe in both cases it will fall back to the "default semantics" of the element, which are provided by setting aria properties on the shadow root. So in both instances the computed state would be checked=true

**Comment by alice** [comment]
Rob is right: the `shadowRoot` properties aren't affected by the ARIA attributes on the host, but are overridden when determining computed properties iff any ARIA attributes are present on the host.

**Comment by caridy** [comment]
That's what I thought! just needed confirmation so @davidturissini can work on some polyfill to try this out.
