### ISSUE TITLE
use case: additive behaviors (aka patterns)

### ISSUE THREAD

**Issue by cyns** [a11y-api/a11y-api#11]
The best example of this is a clickable heading
&lt;h2 onclick="doSomehting();"&gt;My Heading&lt;/h2&gt;

If you add a role to this to tell the user it's clickable, that role overrides the heading role. 
&lt;h2 role="button" onclick="doSomehting();"&gt;My Heading&lt;/h2&gt;

But, usually we want it to be both clickable and a heading.

The UIA concept of a Control Pattern allows adding a set of related methods, states and properties, without changing the Control Type (similar to role). In this case, we would add the Invoke pattern, which includes an Invoke method. 

Here's an overview of UIA Patterns:
https://msdn.microsoft.com/en-us/library/windows/desktop/ee671194(v=vs.85).aspx

**Comment by cookiecrook** [comment]
Can you post that to the "Additive Behaviors" Issue #10. Closing this one as a duplicate.
