### ISSUE TITLE
Why the ARIA attribute overrides the AccessibleNode property?

### ISSUE THREAD

**Issue by Jinjiang** [a11y-api/a11y-api#114]
> When both an AccessibleNode property and its equivalent ARIA attribute are both present, the ARIA attribute overrides the AccessibleNode property.

IMO it's obviously better to override the ARIA attribute by the AccessibleNode property because the AccessibleNode property is more flexible. So is there any reason for this or is it just a mistype?

Thanks.

**Comment by cookiecrook** [comment]
Please comment on the discussion in Issue #98.
