### ISSUE TITLE
Should we expose "accessibility focus" to the web app?

### ISSUE THREAD

**Issue by minorninth** [a11y-api/a11y-api#116]
This is sometimes called "accessibility focus", I'm not sure if there's a better term. Screen readers, switch access, and other AT often has its own focus that isn't necessarily synced with input focus. This allows AT to explore static content, or explore the screen while avoiding focus traps.

Should we expose this to web authors?

We could let the web app know that the user has landed on a node.

Right now most screen readers fire a "scroll into view" event on nodes when they place accessibility focus on them, but this is more of a convention / heuristic, not something the app can rely on.

We should also clarify whether the proposed input event "accessiblefocus" refers to this concept (accessibility focus), or whether it means a normal "set focus" event coming from AT. I was assuming the latter, it means to set input focus on a node.

**Comment by LJWatson** [comment]
The concerns raised in #81 remain relevant here too I think. This feature would give authors a way to identify someone using an AT, and therefore that that person has a disability. This is a serious privacy concern.

**Comment by cookiecrook** [comment]
The AOM focus event was removed previously... Closing this one along with #81
