### ISSUE TITLE
Using serialised AOM as snapshot for UI testing

### ISSUE THREAD

**Issue by arestov** [a11y-api/a11y-api#182]
Is there tool that converts DOM to AOM (that could be run under node.js) ?

I would like to test html/UI without visual and UX unrelated changes. So only UX/accessible changes. Look like converting DOM to AOM for snapshots would be great for me.

I want to make unit/integrated tests that would apply actions to state manager of my webapp. State Manager produces State. State renders (using any kind of DOM manipulating library) DOM (using JSDOM i guess). DOM converts to AOM. 

(thinking of jest that be run under node.js, than my steps to reproduce JSDOM and than i somehow GET AOM that could be serialised to plain simple JSON and saved as snapshot)

**Comment by cookiecrook** [comment]
It hasn’t progressed that far yet. Virtual trees are not yet available and it’s unclear when or if they will be. For the time being, all accessibility info is dependent on the DOM, or in a few cases, CSSOM.

**Comment by eps1lon** [comment]
> Is there tool that converts DOM to AOM (that could be run under node.js) ?

You can convert the DOM to the accessibility tree that browsers use with [`playwright`](https://playwright.dev/docs/api/class-accessibility#accessibility-snapshot) or [`puppeteer`](https://pptr.dev/#?product=Puppeteer&version=v5.3.1&show=api-accessibilitysnapshotoptions).

Note that browsers don't implement the same accessibility tree.
