### ISSUE TITLE
IDL element references attributes names

### ISSUE THREAD

**Issue by mrego** [a11y-api/a11y-api#191]
According to the spec at https://wicg.github.io/aom/spec/aria-reflection.html#AriaAttributes attributes for element references are named without any suffix, e.g. `ariaDescribedBy`.

However that doesn't match the [implementation in Chromium](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/aria_relationship_attributes.idl) that includes a `Elements` suffix, e.g. `ariaDescribedByElements`.

In the ARIA Reflection Explainer, the version with the suffix is used: https://wicg.github.io/aom/aria-reflection-explainer.html#reflecting-element-references

ARIA spec though suggests the name shouldn't have a suffix in a non-normative section: https://w3c.github.io/aria/#idl_attr_disambiguation (filled an issue on ARIA spec too https://github.com/w3c/aria/issues/1724)

**Comment by cookiecrook** [comment]
Since AOM passed reflection off to the ARIA WG to manage, I don't think it's relevant to track it here. Closing. Use https://github.com/w3c/aria/issues/1724
